kind: pipeline
name: default

steps:
- name: testing
  image: plugins/pypi
  environment:
    TEST_DATA_DIR: ../examples/data/
  commands:
    - apk add build-base
    - apk add python3-dev
    - pip3 install -r ./examples/requirements.txt
    - pip3 install -r ./docsource/requirements.txt
    - pip3 install flake8
    - flake8 --statistics --count --ignore=E501
    - make -C docsource clean
    - make -C docsource doctest
    - make -C docsource github

