kind: pipeline
name: default

steps:
# - name: testing
#   image: plugins/pypi
#   environment:
#     TEST_DATA_DIR: ../examples/data/
#   commands:
#     - apk add build-base
#     - apk add python3-dev
#     - pip3 install -r ./examples/requirements.txt
#     - pip3 install -r ./docsource/requirements.txt
#     - pip3 install flake8
#     - flake8 --statistics --count --ignore=E501
#     - make -C docsource clean
#     - make -C docsource doctest
#     - make -C docsource github
###########################################

# - name: submodules
#   image: docker:git
#   environment:
#     SSH_KEY:
#       from_secret: ssh_key
#     SSH_HOST:
#       from_secret: ssh_host
#   commands:
#     # setup ssh for non https git pull
#     - ./building/drone-ssh-helper.sh


- name: test
  image: docker.parasynthetic.dev/karlredman/sphinx-base:latest
  pull: if-not-exists
  commands:
    - ./building/test.sh 3.5.3
    - ./building/test.sh 3.6.8
    - ./building/test.sh 3.7.2

- name: docs_build
  image: docker.parasynthetic.dev/karlredman/sphinx-base:latest
  pull: if-not-exists
  commands:
    - bash -c 'source /root/.bashrc && make -C docsource github'

# - name: deploy
#   image: docker:git
#   environment:
#     # SSH_USER:
#     #   from_secret: ssh_user
#     SSH_KEY:
#       from_secret: ssh_key
#     SSH_HOST:
#       from_secret: ssh_host
#     USER_EMAIL:
#       from_secret: user_email
#     USER_NAME:
#       from_secret: user_name
#     TARGET_REPO:
#       from_secret: target_repo
#   commands:
#     - git config --global user.email "$${USER_EMAIL}"
#     - git config --global user.name "$${USER_NAME}"
#     - ./drone-ssh-helper.sh
