kind: pipeline
name: default

steps:
- name: install
  image: plugins/pypi
  commands:
    # - pip3 install editfrontmatter
    - pip3 install -r ./examples/requirements.txt
    - pip3 install -r ./docsource/requirements.txt
    - make -C docsource clean
    - make -C docsource doctest
    - make -C docsource github

