kind: pipeline
name: default

steps:
- name: install
  image: python:3.5.7-alpine3.9
  commands:
    - pip3 install -r ./examples/requirements.txt
    - pip3 install -r ./docsource/requirements.txt
    - make -C docsource clean
    - make -C docsource doctest
    - make -C docsource github

- name: test
  image: plugins/pypi
  commands:
    - make -C docsource clean
    - make -C docsource doctest

- name: build
  image: plugins/pypi
  commands:
    - make -C docsource github

- name: deploy
  image: docker:git
  environment:
    SSH_KEY:
      from_secret: ssh_key
    SSH_HOST:
      from_secret: ssh_host
  commands:
    - git add -A
    - git commit -am "autobuilt docs"
    - ./util/drone-ssh-helper.sh
