name: Build and Deploy Docs

on:
  push:
    branches:
      # we only deploy docs on master for now -no version checks
      - master
      # - ghpages_deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      # with:
      #   ref: ghpages_deploy

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # install local module
        pip install -e .
        pip install -r docsource/requirements.txt

    - name: Build Sphinx Pages
      run: |
        # bash -c 'source /root/.bashrc && make -C docsource github'
        make -C docsource github
        # cheezy but meh.
        touch site/.nojekyll
        ls -al site
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v1
      with:
        name: site
    - name: deploy site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages # The branch the action should deploy to.
        PUBLISH_DIR: site # The folder the action should deploy.
